export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const CURRENT = 'CURRENT'
export const LOGOUT = 'LOGOUT'
export const GETUSERS = 'GETUSERS'
export const GETONEUSER = 'GETONEUSER'
export const UPDATE_PROFILE_PICTURE_SUCCESS = 'UPDATE_PROFILE_PICTURE_SUCCESS'

